### ISSUE TITLE
GPU加速部分

### ISSUE THREAD

**Issue by lovelyyoshino** [KopiSoftware/VINS_Lite_GPU#1]
您好：
       请问下您修改的内存泄漏部分主要是哪部分的代码呢，目前我在源代码中发现了这个问题。
期待您的回复。

**Comment by KopiSoftware** [comment]
The modification is not in the GPU part but the pose graph node.
Here is the example in the image callback:
```cpp
void image_callback(const sensor_msgs::ImageConstPtr &image_msg)
{
    //ROS_INFO("image_callback!");
    m_buf.lock();
    image_buf.push(image_msg);
    m_buf.unlock();
```
If hold camera still, the image will continue to be added to the vector until the memory is full. Poses callback and point callback are the same. So simply pop out all the redundant massage could fix this problem.
```cpp
#define MAX_BUFF_SIZE 30

void image_callback(const sensor_msgs::ImageConstPtr &image_msg)
{
    //ROS_INFO("image_callback!");
    m_buf.lock();
    while(image_buf.size()>MAX_BUFF_SIZE) image_buf.pop(); 
    image_buf.push(image_msg);
    m_buf.unlock();
```

**Comment by KopiSoftware** [comment]
Also see the [issue](https://github.com/HKUST-Aerial-Robotics/VINS-Fusion/issues/155)

**Comment by lovelyyoshino** [comment]
okey，thank you very much！

**Comment by ZW-PRO** [comment]
Do you have the problem that the memory keeps growing when use vins estimator  without loop ？

**Comment by Idea-in-Dream** [comment]
> 使用无循环的 vins 估算器时，是否遇到内存不断增长的问题？

I also encountered the same problem, have you solved it?

**Comment by Idea-in-Dream** [comment]
> Do you have the problem that the memory keeps growing when use vins estimator without loop ？

I also encountered the same problem, have you solved it?
