### ISSUE TITLE
error: (-217:Gpu API call) no kernel image is available for execution on the device in function 'caller' 

### ISSUE THREAD

**Issue by Rbb666** [KopiSoftware/VINS_Lite_GPU#3]
Hi, I installed opencv3.4.1 and cuda10.1 on Jetson NX  , but when I compile and configure use_ gpu: 1 when running vins-fusion-gpu, this error will be reported. Please help me solve it. Thank you！！！
```
terminate called after throwing an instance of 'cv::Exception'
  what():  OpenCV(3.4.10) /home/rb/opencv-3.4.1/modules/cudafilters/src/cuda/row_filter.hpp:169: error: (-217:Gpu API call) no kernel image is available for execution on the device in function 'caller'

```

**Comment by KopiSoftware** [comment]
I understand. I have tried to follow the Vins GPU original instructions to install opencv3.4.1, but it turns out that 3.4.5 is compatible with it. Highly recommended this version.

**Comment by Rbb666** [comment]
> 我明白。我曾尝试按照 Vins GPU 原始说明安装 opencv3.4.1，但事实证明 3.4.5 与它兼容。强烈推荐这个版本。

@KopiSoftware Thank you very much. I try to change the opencv version to 3.4.5 and it can run. I hope people with the same mistakes as me can see it!!
